apiVersion: v1
kind: Service
metadata:
  name: cccit-service
  namespace: cccit
spec:
  selector:
    app: cccit
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000